In [1]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [2]:
df=pd.read_csv('D:\DATA SCIENCE Internship with Innomatics\Data Analysis\laptop_price.csv')
df.head()

Brand Operating System Processor RAM Type RAM Size Disc Type Disc Size  \
0  Lenovo       Windows 11     Intel     DDR4      8GB       SSD     256GB   
1  Lenovo       Windows 11     Intel     DDR4      8GB       SSD     512GB   
2    ASUS       Windows 11     Intel     DDR4      8GB       SSD     512GB   
3      HP       Windows 10       AMD     DDR4      8GB       SSD     512GB   
4    ASUS       Windows 11     Intel     DDR4      8GB       SSD     512GB   

     MRP  
0  36990  
1  39990  
2  32990  
3  49990  
4  49990

In [3]:
data=df.copy()

In [4]:
data.shape

(720, 8)

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 720 entries, 0 to 719
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   Brand             720 non-null    object
 1   Operating System  720 non-null    object
 2   Processor         720 non-null    object
 3   RAM Type          720 non-null    object
 4   RAM Size          720 non-null    object
 5   Disc Type         720 non-null    object
 6   Disc Size         720 non-null    object
 7   MRP               720 non-null    int64 
dtypes: int64(1), object(7)
memory usage: 45.1+ KB


### Convert categorical columns to numeric column

#### BRAND

In [4]:
data['Brand'].unique()

array(['Lenovo', 'ASUS', 'HP', 'DELL', 'RedmiBook', 'realme', 'acer',
       'MSI', 'APPLE', 'Infinix', 'SAMSUNG', 'Ultimus', 'Vaio',
       'GIGABYTE', 'Nokia', 'ALIENWARE'], dtype=object)

In [5]:
def replace_brand(brand):
    if brand=='Lenovo':
        return 1
    elif brand=='ASUS':
        return 2
    elif brand=='HP':
        return 3
    elif brand=='DELL':
        return 4
    elif brand=='RedmiBook':
        return 5
    elif brand=='realme':
        return 6
    elif brand=='acer':
        return 7
    elif brand=='MSI':
        return 8
    elif brand=='APPLE':
        return 9
    elif brand=='Infinix':
        return 10
    elif brand=='SAMSUNG':
        return 11
    elif brand=='Ultimus':
        return 12
    elif brand=='Vaio':
        return 13
    elif brand=='GIGABYTE':
        return 14
    elif brand=='Nokia':
        return 15
    elif brand=='ALIENWARE':
        return 16
    
data['Brand']=data['Brand'].apply(replace_brand)
data['Brand'].unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16],
      dtype=int64)

#### PROCESSOR TYPE

In [6]:
data['Processor Type'].unique()

array(['Intel Core i3', 'AMD Ryzen 5 Hexa Core', 'Intel Core i5',
       'Intel i3-1115G4', 'AMD Ryzen 7 Quad Core',
       'AMD Ryzen 5 Quad Core', 'AMD Ryzen 9 Octa Core',
       'AMD Ryzen 7 Octa Core', 'Apple M1', 'Intel Celeron Dual Core',
       'AMD Ryzen 3 Dual Core', 'AMD Athlon Dual Core',
       'Intel Evo Core i5', 'AMD Ryzen 3 Quad Core', 'Apple M2',
       'AMD Ryzen R5-5600H', 'Intel Celeron Quad Core', 'Intel Core i7',
       'Apple M1 Pro', 'Qualcomm Snapdragon 7c Gen 2', 'Intel PQC-N5030',
       'Gen Intel Evo Core i5', 'Apple M1 Max', 'Intel Core i9',
       'Intel Pentium Silver', 'Intel i3-1125G4', 'AMD Ryzen 5-3450U',
       'AMD Ryzen 5 Dual Core', 'Intel Core i5-1135G7',
       'Intel Core i3-1005G1', 'Intel Pentium Quad Core',
       'Intel Core i5 Pro', 'AMD Dual Core', 'Intel i7-11800H',
       'AMD Ryzen 3 Hexa Core'], dtype=object)

In [7]:
data['Processor Type'].nunique()

35

#### Create only for Main Type Processors

In [8]:
data['Processor Type']=data['Processor Type'].apply(lambda x: x.replace("Gen ",""))
data[['Processor', 'x','y','z','a']]=data['Processor Type'].str.split(" ", expand=True)
data.drop(['x','y','z','a'], axis=1, inplace=True)
data['Processor'].unique()

array(['Intel', 'AMD', 'Apple', 'Qualcomm'], dtype=object)

In [9]:
data.drop('Processor Type', axis=1, inplace=True)

In [10]:
def replace_processor(Processor):
    if Processor=='Intel':
        return 1
    elif Processor=='AMD':
        return 2
    elif Processor=='Apple':
        return 3
    elif Processor=='Qualcomm':
        return 4
    
data['Processor']=data['Processor'].apply(replace_processor)
data['Processor'].unique()

array([1, 2, 3, 4], dtype=int64)

#### OPERATING SYSTEM

In [11]:
data['Operating System'].unique()

array(['Windows 11', 'Windows 10', 'Mac', 'Chrome', 'DOS'], dtype=object)

In [12]:
def replace_os(os):
    if os=='Windows 11':
        return 1
    elif os=='Windows 10':
        return 2
    elif os=='Mac':
        return 3
    elif os=='Chrome':
        return 4
    elif os=='DOS':
        return 5
    
data['Operating System']=data['Operating System'].apply(replace_os)
data['Operating System'].unique()

array([1, 2, 3, 4, 5], dtype=int64)

#### RAM TYPE

In [13]:
data['RAM Type'].unique()

array(['DDR4', 'DDR5', 'LPDDR4', 'Unified', 'LPDDR4X', 'LPDDR5', 'LPDDR3'],
      dtype=object)

In [14]:
def replace_ram_type(ram_type):
    if ram_type=='DDR4':
        return 1
    elif ram_type=='DDR5':
        return 2
    elif ram_type=='LPDDR4':
        return 3
    elif ram_type=='Unified':
        return 4
    elif ram_type=='LPDDR4X':
        return 5
    elif ram_type=='LPDDR5':
        return 6
    elif ram_type=='LPDDR3':
        return 7
    
data['RAM Type']=data['RAM Type'].apply(replace_ram_type)
data['RAM Type'].unique()

array([1, 2, 3, 4, 5, 6, 7], dtype=int64)

#### RAM SIZE

In [15]:
data['RAM Size'].unique()

array(['8GB', '16GB', '4GB', '32GB'], dtype=object)

In [16]:
def replace_ram_size(ram_size):
    if ram_size=='8GB':
        return 1
    elif ram_size=='16GB':
        return 2
    elif ram_size=='4GB':
        return 3
    elif ram_size=='32GB':
        return 4

    
data['RAM Size']=data['RAM Size'].apply(replace_ram_size)
data['RAM Size'].unique()

array([1, 2, 3, 4], dtype=int64)

#### DISC TYPE

In [17]:
data['Disc Type'].unique()

array(['SSD', 'HDD', 'EMMC'], dtype=object)

In [18]:
def replace_disc_type(disc_type):
    if disc_type=='SSD':
        return 1
    elif disc_type=='HDD':
        return 2
    elif disc_type=='EMMC':
        return 3

    
data['Disc Type']=data['Disc Type'].apply(replace_disc_type)
data['Disc Type'].unique()

array([1, 2, 3], dtype=int64)

#### DISC SIZE

In [19]:
data['Disc Size'].unique()

array(['256GB', '512GB', '1TB', '128GB', '64GB', '32GB', '2TB'],
      dtype=object)

In [20]:
def replace_disc_size(disc_size):
    if disc_size=='256GB':
        return 1
    elif disc_size=='512GB':
        return 2
    elif disc_size=='1TB':
        return 3
    elif disc_size=='128GB':
        return 4
    elif disc_size=='64GB':
        return 5
    elif disc_size=='32GB':
        return 6
    elif disc_size=='2TB':
        return 7
    
data['Disc Size']=data['Disc Size'].apply(replace_disc_size)
data['Disc Size'].unique()

array([1, 2, 3, 4, 5, 6, 7], dtype=int64)

In [21]:
data.head()

Brand  Operating System  RAM Type  RAM Size  Disc Type  Disc Size    MRP  \
0      1                 1         1         1          1          1  36990   
1      1                 1         1         1          1          2  39990   
2      2                 1         1         1          1          2  32990   
3      3                 2         1         1          1          2  49990   
4      2                 1         1         1          1          2  49990   

   Processor  
0          1  
1          1  
2          1  
3          2  
4          1

In [22]:
data.isna().sum()

Brand               0
Operating System    0
RAM Type            0
RAM Size            0
Disc Type           0
Disc Size           0
MRP                 0
Processor           0
dtype: int64

### Split into dependent and independent

In [23]:
X=data.drop('MRP', axis=1).values
y=data['MRP'].values

In [24]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler
std=StandardScaler()
X=std.fit_transform(X)

print(X)

[[-0.80688224 -0.46911664 -0.42107258 ... -0.28058001 -1.45873792
  -0.87423048]
 [-0.80688224 -0.46911664 -0.42107258 ... -0.28058001 -0.31711694
  -0.87423048]
 [-0.44104142 -0.46911664 -0.42107258 ... -0.28058001 -0.31711694
  -0.87423048]
 ...
 [-0.44104142 -0.46911664  0.46281156 ... -0.28058001  0.82450404
   0.91906281]
 [-0.44104142 -0.46911664  3.99834813 ... -0.28058001 -0.31711694
  -0.87423048]
 [-0.80688224  1.21970327 -0.42107258 ...  2.69026717  0.82450404
  -0.87423048]]


### Split into training and testing set

In [25]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(576, 7)
(576,)
(144, 7)
(144,)


### Machine Learning Regression Models

### 1. Linear Regression

In [26]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr=lr.fit(x_train,y_train)
y_pred=lr.predict(x_test)

In [27]:
from sklearn.metrics import mean_squared_error as mse, r2_score

MSE=mse(y_pred,y_test).round(2)
RMSE=np.sqrt(MSE).round(2)
R2=r2_score(y_pred, y_test)

results=pd.DataFrame({"Model":["Linear Regression"], "MSE":[MSE], "RMSE":[RMSE], "R2 Score":[R2]})
results

Model           MSE      RMSE  R2 Score
0  Linear Regression  1.165097e+09  34133.52  0.517662

### 2. Decision Tree

In [28]:
from sklearn.tree import DecisionTreeRegressor

dt=DecisionTreeRegressor(random_state=0)
dt.fit(x_train,y_train)
y_pred=dt.predict(x_test)

In [29]:
MSE=mse(y_pred,y_test).round(2)
RMSE=np.sqrt(MSE).round(2)
R2=r2_score(y_pred, y_test)

result=pd.DataFrame({"Model":["Decision Tree Regression"], "MSE":[MSE], "RMSE":[RMSE], "R2 Score":[R2]})

results=pd.concat([results,result])
results

Model           MSE      RMSE  R2 Score
0         Linear Regression  1.165097e+09  34133.52  0.517662
0  Decision Tree Regression  5.533518e+08  23523.43  0.846429

### 3. Random Forest

In [30]:
from sklearn.ensemble import RandomForestRegressor

rf=RandomForestRegressor(n_estimators=100)
rf.fit(x_train,y_train)
y_pred=rf.predict(x_test)

In [31]:
MSE=mse(y_pred,y_test).round(2)
RMSE=np.sqrt(MSE).round(2)
R2=r2_score(y_pred, y_test)

result=pd.DataFrame({"Model":["Random Forest Regression"], "MSE":[MSE], "RMSE":[RMSE], "R2 Score":[R2]})

results=pd.concat([results,result])
results

Model           MSE      RMSE  R2 Score
0         Linear Regression  1.165097e+09  34133.52  0.517662
0  Decision Tree Regression  5.533518e+08  23523.43  0.846429
0  Random Forest Regression  5.814653e+08  24113.59  0.836842

### 4. Gradient boosting

In [32]:
from sklearn.ensemble import GradientBoostingRegressor

grb= GradientBoostingRegressor(n_estimators =100,random_state =0) 
grb.fit(x_train, y_train) 
y_pred = grb.predict(x_test)

In [33]:
MSE=mse(y_pred,y_test).round(2)
RMSE=np.sqrt(MSE).round(2)
R2=r2_score(y_pred, y_test)

result=pd.DataFrame({"Model":["Gradient Boosting Regression"], "MSE":[MSE], "RMSE":[RMSE], "R2 Score":[R2]})

results=pd.concat([results,result])
results

Model           MSE      RMSE  R2 Score
0             Linear Regression  1.165097e+09  34133.52  0.517662
0      Decision Tree Regression  5.533518e+08  23523.43  0.846429
0      Random Forest Regression  5.814653e+08  24113.59  0.836842
0  Gradient Boosting Regression  5.494580e+08  23440.52  0.862283

### 5. ADA Boost

In [34]:
from sklearn.ensemble import AdaBoostRegressor

ada=AdaBoostRegressor(n_estimators=100,learning_rate=0.001,random_state=0)
ada.fit(x_train,y_train)
y_pred=ada.predict(x_test)

In [35]:
MSE=mse(y_pred,y_test).round(2)
RMSE=np.sqrt(MSE).round(2)
R2=r2_score(y_pred, y_test)

result=pd.DataFrame({"Model":["ADA Boost Regression"], "MSE":[MSE], "RMSE":[RMSE], "R2 Score":[R2]})

results=pd.concat([results,result])
results

Model           MSE      RMSE  R2 Score
0             Linear Regression  1.165097e+09  34133.52  0.517662
0      Decision Tree Regression  5.533518e+08  23523.43  0.846429
0      Random Forest Regression  5.814653e+08  24113.59  0.836842
0  Gradient Boosting Regression  5.494580e+08  23440.52  0.862283
0          ADA Boost Regression  7.632972e+08  27627.83  0.744935

### XG boost

In [36]:
from xgboost import XGBRegressor

xgb=XGBRegressor(verbosity=0) 
xgb.fit(x_train,y_train)
y_pred=xgb.predict(x_test)

In [37]:
MSE=mse(y_pred,y_test).round(2)
RMSE=np.sqrt(MSE).round(2)
R2=r2_score(y_pred, y_test)

result=pd.DataFrame({"Model":["XG Boost Regression"], "MSE":[MSE], "RMSE":[RMSE], "R2 Score":[R2]})

results=pd.concat([results,result])
results

Model           MSE      RMSE  R2 Score
0             Linear Regression  1.165097e+09  34133.52  0.517662
0      Decision Tree Regression  5.533518e+08  23523.43  0.846429
0      Random Forest Regression  5.814653e+08  24113.59  0.836842
0  Gradient Boosting Regression  5.494580e+08  23440.52  0.862283
0          ADA Boost Regression  7.632972e+08  27627.83  0.744935
0           XG Boost Regression  5.649962e+08  23769.65  0.845916

### XG boost regressor has high R2 score and low RMSE, tune this model and select this to predict the price of Laptop.

In [38]:
xgb=XGBRegressor(learning_rate=0.15, n_estimators=50, max_leaves=0, random_state=42)

xgb.fit(x_train,y_train)
y_pred=xgb.predict(x_test)

print(mse(y_pred,y_test).round(2))
print(np.sqrt(mse(y_pred,y_test).round(2)))
print(((r2_score(y_pred, y_test))*100).round(2),'%')

457971928.85
21400.27870963367
86.84 %


### Cross validation to check model performace

In [39]:
from sklearn.model_selection import cross_val_score, KFold, ShuffleSplit

xgb=XGBRegressor(learning_rate=0.15, n_estimators=50, max_leaves=0, random_state=42)

k=ShuffleSplit(n_splits=20, test_size=0.2, random_state=20)
score=cross_val_score(xgb, X,y, cv=k)
print("Cross validations Score:\n", score)
print("Average Cross validations Score:", score.mean())
print("Maximum Cross validations Score:", score.max())
print("Minimum Cross validations Score:", score.min())

Cross validations Score:
 [0.8603306  0.80200795 0.87746295 0.88874028 0.87624929 0.8825799
 0.76237864 0.8513186  0.84415186 0.80778223 0.7615706  0.86066386
 0.87742852 0.83614981 0.79473697 0.86295514 0.86354206 0.88329833
 0.88926268 0.8445585 ]
Average Cross validations Score: 0.8463584395475351
Maximum Cross validations Score: 0.8892626827893856
Minimum Cross validations Score: 0.7615705985881537


### Applying cross validation not improving model performance.

### Save model as pickle object

In [40]:
import pickle
pickle.dump(xgb, open('laptop_price_prediction_model.pkl', 'wb'))

## Using Encoding (OneHotEncoding/Dummies)

In [41]:
data=df.copy()

In [42]:
data.head()

Brand         Processor Type Operating System RAM Type RAM Size Disc Type  \
0  Lenovo          Intel Core i3       Windows 11     DDR4      8GB       SSD   
1  Lenovo          Intel Core i3       Windows 11     DDR4      8GB       SSD   
2    ASUS          Intel Core i3       Windows 11     DDR4      8GB       SSD   
3      HP  AMD Ryzen 5 Hexa Core       Windows 10     DDR4      8GB       SSD   
4    ASUS          Intel Core i5       Windows 11     DDR4      8GB       SSD   

  Disc Size    MRP  
0     256GB  36990  
1     512GB  39990  
2     512GB  32990  
3     512GB  49990  
4     512GB  49990

In [43]:
data['Processor Type'].unique()

array(['Intel Core i3', 'AMD Ryzen 5 Hexa Core', 'Intel Core i5',
       'Intel i3-1115G4', 'AMD Ryzen 7 Quad Core',
       'AMD Ryzen 5 Quad Core', 'AMD Ryzen 9 Octa Core',
       'AMD Ryzen 7 Octa Core', 'Apple M1', 'Intel Celeron Dual Core',
       'AMD Ryzen 3 Dual Core', 'AMD Athlon Dual Core',
       'Intel Evo Core i5', 'AMD Ryzen 3 Quad Core', 'Apple M2',
       'AMD Ryzen R5-5600H', 'Intel Celeron Quad Core', 'Intel Core i7',
       'Apple M1 Pro', 'Qualcomm Snapdragon 7c Gen 2', 'Intel PQC-N5030',
       'Gen Intel Evo Core i5', 'Apple M1 Max', 'Intel Core i9',
       'Intel Pentium Silver', 'Intel i3-1125G4', 'AMD Ryzen 5-3450U',
       'AMD Ryzen 5 Dual Core', 'Intel Core i5-1135G7',
       'Intel Core i3-1005G1', 'Intel Pentium Quad Core',
       'Intel Core i5 Pro', 'AMD Dual Core', 'Intel i7-11800H',
       'AMD Ryzen 3 Hexa Core'], dtype=object)

### Create only 4 Main Processor type using above values

In [44]:
data['Processor Type']=data['Processor Type'].apply(lambda x: x.replace("Gen ",""))

In [45]:
data[['Processor', 'x','y','z','a']]=data['Processor Type'].str.split(" ", expand=True)

In [46]:
data.drop(['x','y','z','a'], axis=1, inplace=True)
data['Processor'].unique()

array(['Intel', 'AMD', 'Apple', 'Qualcomm'], dtype=object)

### We have created new column which contains main Processor type, hence drop old processor type column

In [47]:
data.drop('Processor Type', axis=1, inplace=True)

In [48]:
data=data[['Brand', 'Operating System', 'Processor','RAM Type', 'RAM Size', 'Disc Type', 'Disc Size', 'MRP']]

In [49]:
data.head()

Brand Operating System Processor RAM Type RAM Size Disc Type Disc Size  \
0  Lenovo       Windows 11     Intel     DDR4      8GB       SSD     256GB   
1  Lenovo       Windows 11     Intel     DDR4      8GB       SSD     512GB   
2    ASUS       Windows 11     Intel     DDR4      8GB       SSD     512GB   
3      HP       Windows 10       AMD     DDR4      8GB       SSD     512GB   
4    ASUS       Windows 11     Intel     DDR4      8GB       SSD     512GB   

     MRP  
0  36990  
1  39990  
2  32990  
3  49990  
4  49990

In [59]:
data.to_csv("laptop_price.csv", index=False)

### Create dummies for all Categorical column

In [50]:
pd.options.display.max_columns=100

In [51]:
data1=pd.get_dummies(data)
data1.head()

MRP  Brand_ALIENWARE  Brand_APPLE  Brand_ASUS  Brand_DELL  \
0  36990                0            0           0           0   
1  39990                0            0           0           0   
2  32990                0            0           1           0   
3  49990                0            0           0           0   
4  49990                0            0           1           0   

   Brand_GIGABYTE  Brand_HP  Brand_Infinix  Brand_Lenovo  Brand_MSI  \
0               0         0              0             1          0   
1               0         0              0             1          0   
2               0         0              0             0          0   
3               0         1              0             0          0   
4               0         0              0             0          0   

   Brand_Nokia  Brand_RedmiBook  Brand_SAMSUNG  Brand_Ultimus  Brand_Vaio  \
0            0                0              0              0           0   
1            0                0              0              0           0   
2            0                0              0              0           0   
3            0                0              0              0           0   
4            0                0              0              0           0   

   Brand_acer  Brand_realme  Operating System_Chrome  Operating System_DOS  \
0           0             0                        0                     0   
1           0             0                        0                     0   
2           0             0                        0                     0   
3           0             0                        0                     0   
4           0             0                        0                     0   

   Operating System_Mac  Operating System_Windows 10  \
0                     0                            0   
1                     0                            0   
2                     0                            0   
3                     0                            1   
4                     0                            0   

   Operating System_Windows 11  Processor_AMD  Processor_Apple  \
0                            1              0                0   
1                            1              0                0   
2                            1              0                0   
3                            0              1                0   
4                            1              0                0   

   Processor_Intel  Processor_Qualcomm  RAM Type_DDR4  RAM Type_DDR5  \
0                1                   0              1              0   
1                1                   0              1              0   
2                1                   0              1              0   
3                0                   0              1              0   
4                1                   0              1              0   

   RAM Type_LPDDR3  RAM Type_LPDDR4  RAM Type_LPDDR4X  RAM Type_LPDDR5  \
0                0                0                 0                0   
1                0                0                 0                0   
2                0                0                 0                0   
3                0                0                 0                0   
4                0                0                 0                0   

   RAM Type_Unified  RAM Size_16GB  RAM Size_32GB  RAM Size_4GB  RAM Size_8GB  \
0                 0              0              0             0             1   
1                 0              0              0             0             1   
2                 0              0              0             0             1   
3                 0              0              0             0             1   
4                 0              0              0             0             1   

   Disc Type_EMMC  Disc Type_HDD  Disc Type_SSD  Disc Size_128GB  \
0               0              0              1                0   
1             

In [52]:
X=data1.drop("MRP", axis=1).values
y=data1["MRP"].values

In [53]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.2, random_state=0)

In [54]:
from sklearn.ensemble import RandomForestRegressor

rf=RandomForestRegressor()
rf=rf.fit(x_train,y_train)
y_pred=rf.predict(x_test)

In [55]:
from sklearn.metrics import r2_score, mean_squared_error

print(r2_score(y_pred,y_test))

0.8898321803157054


In [56]:
from xgboost import XGBRegressor

xgb=XGBRegressor(n_estimators=100,max_depth=2, max_leaves=2, booster='gbtree', learning_rate=0.19)
xgb=xgb.fit(x_train,y_train)
y_pred=xgb.predict(x_test)

In [57]:
print(r2_score(y_pred,y_test))

0.9194503254451336


In [58]:
from sklearn.model_selection import cross_val_score, KFold, ShuffleSplit

xgb=XGBRegressor(n_estimators=100,max_depth=2, max_leaves=2, booster='gbtree', learning_rate=0.19)

k=ShuffleSplit(n_splits=20, test_size=0.2, random_state=0)
score=cross_val_score(xgb, X,y, cv=k)
print("Cross validations Score:\n", score)
print("Average Cross validations Score:", score.mean())
print("Maximum Cross validations Score:", score.max())
print("Minimum Cross validations Score:", score.min())

Cross validations Score:
 [0.91495966 0.86168018 0.87582945 0.87495164 0.75954796 0.8584843
 0.85802864 0.861162   0.89802215 0.89467985 0.90591489 0.9027385
 0.80068514 0.87119416 0.84570491 0.90027658 0.91734123 0.89167961
 0.8737434  0.86210028]
Average Cross validations Score: 0.8714362267743091
Maximum Cross validations Score: 0.9173412332283342
Minimum Cross validations Score: 0.7595479639635282


### The model performace Increased little bit.